### ISSUE TITLE
Autofetch mod names

### ISSUE THREAD

**Issue by GhoulofGSG9** [keatsandyeats/Shine-ModSelector#12]
Users really shouldn't have to enter the steamworks modification names. Just fetch them directly from the workshop via the steam web api (e.g via https://api.steampowered.com/IPublishedFileService/GetDetails/v1/?publishedfileids[0]=750692218&key=key)

Of course the user would still need to provide their own api key but that shouldn't be an issue as some other shine features already rely on it?

Also this way you could provide more details about each mod from inside the menu.

**Comment by keatsandyeats** [comment]
This is a great suggestion, thank you. I will look into this.

**Comment by keatsandyeats** [comment]
closed with 8228fe05be176bc18e27fbfee050f41ab9962426
